<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            margin: 20px 25px;
        }

        .header {
            text-align: center;
            margin-bottom: 15px;
            position: relative;
        }

        .header img.left-logo {
            position: absolute;
            left: 0;
            top: 0;
            width: 120px;
        }

        .header img.right-logo {
            position: absolute;
            right: 0;
            top: 0;
            width: 120px;
        }

        .header-title {
            margin: 0;
            margin-bottom: 15px;
            font-size: 20px;
            text-transform: uppercase;
        }

        .sub-title {
            margin: 2px 0 0 0;
            font-size: 18px;
            font-weight: normal;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            page-break-inside: auto;
        }

        table thead th {
            background: #eaeaea;
            border: 1px solid #000;
            font-size: 13px;
            padding: 6px;
            text-align: center;
        }

        table tbody td {
            border: 1px solid #000;
            padding: 5px;
            vertical-align: top;
            font-size: 11px;
        }

        table tbody tr:nth-child(even) {
            background: #f9f9f9;
        }

        .category-row td {
            background: #cfcfcf;
            font-weight: bold;
            font-size: 12px;
            text-transform: uppercase;
            text-align: left;
            padding: 5px;
        }

        .grand-total-row td {
            background: #f0f0f0;
            font-weight: bold;
        }

        .footer {
            margin-top: 20px;
            text-align: right;
            font-size: 10px;
            position: relative;
        }

        .footer .page-number:after {
            content: counter(page);
        }

        @page {
            margin: 20px 25px;
            counter-increment: page;
        }
    </style>
</head>

<body>

    <!-- HEADER -->
    <div class="header">
        <img src="{{ public_path('images/logo2.png') }}" class="left-logo" alt="Left Logo">
        <img src="{{ public_path('images/InvestPH.png') }}" class="right-logo" alt="Right Logo">

        <p class="header-title">
            Report on Employment for <br> Clark Freeport Zone
        </p>

    </div>

    <!-- DETAILS TABLE (no borders) -->
    <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
        <tbody>
            <tr>
                <td style="border: none; padding: 4px; font-size: 12px"><strong>Period / Month:</strong></td>
                <td style="border: none; padding: 4px; font-size: 12px">
                    {{ \Carbon\Carbon::createFromFormat('m', $filters['month'])->format('F') }}
                </td>
            </tr>
            <tr style="background: #fff;">
                <td style="border: none; padding: 4px; font-size: 12px"><strong>Name of CFZ Enterprise:</strong></td>
                <td style="border: none; padding: 4px; font-size: 12px">{{ $records->user->name }}</td>
            </tr>
        </tbody>
    </table>


    <!-- EMPLOYEES TABLE -->
    <table>
        <thead>
            <tr>
                <th style="width: 3%;">No.</th>
                <th style="width: 30%;">Employee Name</th>
                <th style="width: 20%;">Position / Rank</th>
                <th style="width: 27%;">Nationality</th>
                <th style="width: 10%; font-size: 11px">Regular</th>
                <th style="width: 10%; font-size: 11px">Probationary</th>
                <th style="width: 10%; font-size: 11px">Contractual</th>
            </tr>
        </thead>

        <tbody>
            @forelse ($records->details as $index => $data)
                <tr>
                    <td style="text-align: center;">{{ $index + 1 }}</td>
                    <td>{{ $data->name ?? 'N/A' }}</td>
                    <td>{{ $data->position ?? 'N/A' }}</td>
                    <td>{{ $data->nationality ?? 'N/A' }}</td>
                    <td style="text-align: center;">{{ $data->status == 'Regular' ? 'X' : '' }}</td>
                    <td style="text-align: center;">{{ $data->status == 'Probationary' ? 'X' : '' }}</td>
                    <td style="text-align: center;">{{ $data->status == 'Contractual' ? 'X' : '' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center;">No employee found.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <!-- FOOTER -->
    <div class="footer">
        Report generated by {{ auth()->user()->name ?? 'System' }} | Page <span class="page-number"></span>
    </div>

</body>

</html>
