<!DOCTYPE html>
<html>

<head>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            margin: 20px 25px;
        }

        .header {
            text-align: center;
            margin-bottom: 10px;
            position: relative;
        }

        .header img.left-logo {
            position: absolute;
            left: 0;
            top: 0;
            width: 150px;
        }

        .header img.right-logo {
            position: absolute;
            right: 0;
            top: 0;
            width: 150px;
        }

        h2 {
            margin: 0;
            font-size: 20px;
            font-weight: bold;
        }

        h4 {
            margin: 2px 0 0 0;
            font-size: 13px;
            font-weight: normal;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            page-break-inside: auto;
        }

        table thead th {
            background: #eaeaea;
            border: 1px solid #000;
            font-size: 11px;
            padding: 5px;
            text-align: center;
        }

        table tbody td {
            border: 1px solid #000;
            padding: 4px;
            vertical-align: top;
            font-size: 11px;
        }

        .category-row td {
            background: #cfcfcf;
            font-weight: bold;
            font-size: 12px;
            text-transform: uppercase;
            text-align: left;
            padding: 5px;
        }

        .grand-total-row td {
            background: #f0f0f0;
            font-weight: bold;
        }

        .footer {
            margin-top: 15px;
            text-align: right;
            font-size: 11px;
        }

        @page {
            margin: 20px 25px;
        }
    </style>
</head>

<body>

    <!-- HEADER -->
    <div class="header">
        <img src="{{ public_path('images/logo2.png') }}" class="left-logo">
        <img src="{{ public_path('images/logo1.png') }}" class="right-logo">

        <p
            style="
        margin: 0;
        font-size: 15px;
        font-weight: bold;
        text-transform: uppercase;
        letter-spacing: 1px;
    ">
            CLARK FREEPORT ZONE
        </p>

        <p style="
        margin: -5px -0 -0 -0;
        font-size: 30px;
        font-weight: bold;
    ">
            {{ $title }}
        </p>

        <p style="
        margin: -5px -0 -0 -0;
        font-size: 16px;
    ">
            <i> as of {{ $generated_at }}</i>
        </p>
    </div>

    @php
        $groupedVacancies = $records
            ->sortBy(fn($job) => $job->category->name ?? 'Unknown')
            ->groupBy(fn($job) => $job->category->name ?? 'Uncategorized');

        $grandTotal = $records->sum('available');
    @endphp

    <!-- TABLE -->
    <table>
        <thead>
            <tr>
                <th>COMPANY NAME</th>
                <th>POSITION</th>
                <th>EDUCATIONAL REQUIREMENT</th>
                <th>WORK EXPERIENCE</th>
                <th style="font-size: 14px">MINIMUM QUALIFICATION</th>
                <th># OF VACANT POSITION</th>
            </tr>
        </thead>

        <tbody>
            @forelse ($groupedVacancies as $categoryName => $jobs)
                <tr class="category-row">
                    <td colspan="6">{{ $categoryName }}</td>
                </tr>

                @foreach ($jobs as $job)
                    <tr>
                        <td>{{ $job->employer->user->name ?? 'N/A' }}</td>
                        <td>{{ $job->title }}</td>
                        <td>{{ $job->jobQualify->name ?? 'N/A' }}</td>
                        <td>{{ $job->jobExperience->name ?? 'N/A' }}</td>
                        <td>{!! nl2br(strip_tags($job->qualifications, '<b><i>')) !!}</td>
                        <td style="text-align:center;">{{ $job->available ?? 0 }}</td>
                    </tr>
                @endforeach
            @empty
                <tr>
                    <td colspan="6" style="text-align: center;">No job vacancies found.</td>
                </tr>
            @endforelse

            @if ($records->count() > 0)
                <tr class="grand-total-row">
                    <td colspan="5">Overall Total Vacancies</td>
                    <td style="text-align:center;">{{ $grandTotal }}</td>
                </tr>
            @endif
        </tbody>
    </table>

    <!-- FOOTER -->
    <div class="footer">
        Report generated by {{ auth()->user()->name ?? 'System' }}
    </div>

</body>

</html>
