<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            color: #333;
            font-size: 12px;
            position: relative;
        }

        .header {
            position: relative;
            text-align: center;
            margin-bottom: 20px;
        }

        .header img.left-logo {
            position: absolute;
            left: 0;
            top: 0;
            height: 50px;
            width: auto;
        }

        .header img.right-logo {
            position: absolute;
            right: 0;
            top: 0;
            height: 50px;
            width: auto;
        }

        h2 {
            margin: 0;
            font-size: 18px;
        }

        h4 {
            text-align: center;
            margin-top: 5px;
            font-weight: normal;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #ccc;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f8f9fa;
        }

        .category-row {
            background-color: #e9ecef;
            font-weight: bold;
            text-transform: uppercase;
            text-align: center;
        }

        .grand-total-row {
            background-color: #f1f3f5;
            font-weight: bold;
            text-align: center;
        }

        .footer {
            text-align: right;
            font-size: 10px;
            margin-top: 15px;
            color: #777;
        }
    </style>
</head>

<body>

    <div class="header">
        <img src="{{ public_path('images/logo2.png') }}" class="left-logo" alt="Left Logo">
        <img src="{{ public_path('images/logo1.png') }}" class="right-logo" alt="Right Logo">
        <h2>{{ $title }}</h2>
        <h4 style="margin-top: -2px">
            as of {{ $generated_at }} <br>
            Date Range: {{ $filters['dateRange'] }}
        </h4>
    </div>


    @php
        // ✅ Group vacancies by category and sort alphabetically
        $groupedVacancies = $vacancies
            ->sortBy(fn($job) => $job->category->name ?? 'Unknown')
            ->groupBy(fn($job) => $job->category->name ?? 'Uncategorized');

        // ✅ Compute grand total of available vacancies
        $grandTotal = $vacancies->sum('available');
    @endphp

    <table>
        <thead>
            <tr>
                <th>Company Name</th>
                <th>Position</th>
                <th>Qualification</th>
                <th>Work Experience</th>
                <th>Salary</th>
                <th>Vacants</th>
            </tr>
        </thead>

        <tbody>
            @forelse ($groupedVacancies as $categoryName => $jobs)
                <tr class="category-row">
                    <td colspan="6">{{ $categoryName }}</td>
                </tr>

                @foreach ($jobs as $job)
                    <tr>
                        <td>{{ $job->employer->user->name ?? 'N/A' }}</td>
                        <td>{{ $job->title }}</td>
                        <td>{{ $job->jobQualify->name ?? 'N/A' }}</td>
                        <td>{{ $job->job_experience ? $job->job_experience . ' year(s)' : 'N/A' }}</td>
                        <td>{{ $job->salary ?? 'N/A' }}</td>
                        <td>{{ $job->available ?? 0 }}</td>
                    </tr>
                @endforeach
            @empty
                <tr>
                    <td colspan="6" style="text-align: center;">No job vacancies found.</td>
                </tr>
            @endforelse

            @if ($vacancies->count() > 0)
                <tr class="grand-total-row">
                    <td colspan="5">Overall Total Vacancies</td>
                    <td>{{ $grandTotal }}</td>
                </tr>
            @endif
        </tbody>
    </table>

    <div class="footer">
        <p>Report generated by {{ auth()->user()->name ?? 'System' }}</p>
    </div>

</body>

</html>
