<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            color: #333;
            font-size: 12px;
            position: relative;
        }

        .header {
            position: relative;
            text-align: center;
            margin-bottom: 20px;
        }

        .header img.left-logo {
            position: absolute;
            left: 0;
            top: 0;
            height: 50px;
            width: auto;
        }

        .header img.right-logo {
            position: absolute;
            right: 0;
            top: 0;
            height: 50px;
            width: auto;
        }

        h2 {
            margin: 0;
            font-size: 18px;
        }

        h4 {
            text-align: center;
            margin-top: 5px;
            font-weight: normal;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid #ccc;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f8f9fa;
        }

        .role-row {
            background-color: #e9ecef;
            font-weight: bold;
            text-transform: uppercase;
            text-align: center;
        }

        .footer {
            text-align: right;
            font-size: 10px;
            margin-top: 15px;
            color: #777;
        }
    </style>
</head>

<body>

    <div class="header">
        <img src="{{ public_path('images/logo2.png') }}" class="left-logo" alt="Left Logo">
        <img src="{{ public_path('images/logo1.png') }}" class="right-logo" alt="Right Logo">
        <h2>{{ $title }}</h2>
        <h4 style="margin-top: -2px">
            as of {{ $generated_at }} <br>
            Date Range: {{ $filters['dateRange'] ?? 'All Dates' }}
        </h4>
    </div>

    @php
        // ✅ Group users by role (optional)
        $groupedUsers = $users->groupBy(fn($user) => ucfirst($user->user_type ?? 'Unspecified'));
    @endphp

    <table>
        <thead>
            <tr>
                <th style="width: 25%;">Name</th>
                <th style="width: 25%;">Email</th>
                <th style="width: 25%;">Address</th>
                <th style="width: 25%;">Contact #</th>
            </tr>
        </thead>

        <tbody>
            @forelse ($groupedUsers as $role => $userGroup)
                <tr class="role-row">
                    <td colspan="4">{{ str_replace('_', ' ', $role) }}</td>
                </tr>

                @foreach ($userGroup as $user)
                    <tr>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->address ?? 'N/A' }}</td>
                        <td>{{ $user->telephone ?? 'N/A' }}</td>
                    </tr>
                @endforeach
            @empty
                <tr>
                    <td colspan="4" style="text-align:center;">No users found for the selected filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>Report generated by {{ auth()->user()->name ?? 'System' }}</p>
    </div>

</body>

</html>
